### ISSUE TITLE
Add @Service for HttpClient annotation

### ISSUE THREAD

**Issue by linux-china** [maciejwalkowiak/spring-boot-http-clients#1]
Now if you refer  HTTP Interface as bean in IntelliJ IDEA, and IDEA will report `Could not autowire. No beans of 'HttpBinService' type found. `. 

<img width="810" alt="Screenshot 2023-04-05 at 5 41 02 PM" src="https://user-images.githubusercontent.com/46711/230044728-f80f5ba1-60b1-4e94-b802-da992255ee5b.png">

spring-boot-http-clients relies on Spring, and `@Service` could be added in HttpClient annotation, and make HTTP interface as a bean.

```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.TYPE})
@Documented
@Service
public @interface HttpClient {

    /**
     * Name of the {@link WebClient} bean to use with http client
     * @return bean name
     */
    String value();
}
```

**Comment by uladzislau-ulasovich** [comment]
Could you please show what's inside of the `HttpBinService`?

**Comment by linux-china** [comment]
@uladzislau-ulasovich  The code as following:

```java
@HttpClient("httpbin-client")
public interface HttpBinService {
    @GetExchange("/ip")
    Mono<MyIp> myIp();

    record MyIp(String origin) {
    }
}

```

**Comment by uladzislau-ulasovich** [comment]
But have you tried to run the code?

IntelliJ might complain about missing bean definition just because it doesn't know anything about `@HttpClient`, and that classes annotated with `@HttpClient` will become beans.

Spring work in exactly the same way, during startup it just scans for classes annotated with `@Component`, `@Bean`, `@Service`, etc, then create bean definitions, factories, and then create beans. Annotations itself, without a code that knows how to use them, is just a meta data, they do nothing.

**Comment by linux-china** [comment]
If you add a `@Service` on HTTP interface, and IDEA will treat the interface as bean. 

```java
@HttpClient("httpbin-client")
@Service
public interface HttpBinService {
    @GetExchange("/ip")
    Mono<MyIp> myIp();

    record MyIp(String origin) {
    }
}
```

**Comment by maciejwalkowiak** [comment]
Adding a @Service also makes the interface a subject to all sorts of annotation processing that search for service annotations. 

Perhaps there is a better way to make Intellij recognize these beans - some extra metadata?

**Comment by uladzislau-ulasovich** [comment]
@linux-china you see this error only because the Spring plugin in your IDE knows only about annotations from Spring. Adding `@Service` annotation does not solve any problem at all (because there are no problem). As @maciejwalkowiak mentioned, it might make things even worse.

> Spring HTTP Interface just an interface, and these is no class to implement the HTTP interface at all

Also not true, Spring will create proxies with implementation of http client. I'm 90% sure it works exactly the same as Spring Data JPA Repositories.

@maciejwalkowiak it seems like it's known problem that IntelliJ IDEA (the Spring plugin especially) doesn't recognize custom Beans as candidates for injection. It also does not show a gutter icon to jump to bean definition. I think there should be a way to somehow provide a meta-data to make it works in a nice way, I'm looking into this.

**Comment by maciejwalkowiak** [comment]
I hope Intellij figures out better how to detect beans registered in less usual way. I've decided to not add any stereotype annotation as it could have side effects that are not welcome.
